title: ∫created - Sergey Polyarus
email: your-email@example.com
description: Developpeur Fullstack en freelance Java, Kotlin, SpringBoot, Angular
header:
  title: ∫created - Sergey Polyarus
  description: >- # this means to ignore newlines until "baseurl:"
    Developpeur Fullstack en freelance  SpringBoot / Angular

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://icreated.fr"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# theme: minima
plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

defaults:
  - scope:
      path: assets/**
    values:
      sitemap: false


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
social:
  github: icreated
  linkedin: sergey-polyarus-23537a4a
  stackoverflow: spok
  credly: sergey-polyarus
  youtube: SergeyPolyarus

icreated:
  location: LYON, FRANCE
  links:
    github:
      title: github
      url: https://github.com/icreated
    blog:
      title: Blog Icreated
      url: https://icreated.co
    credly:
      title: Credly
      url: https://www.credly.com/users/sergey-polyarus/badges
    youtube:
      title: YouTube
      url: https://www.youtube.com/@SergeyPolyarus/videos   

collections:
  skills:
    output: false
  soft_skills:
    output: false
  projects:
    output: true
    permalink: /project/:path/
  experiences:
    output: false
  certifications:
    output: true
    permalink: /certification/:path/
  education:
    output: false
  languages:
    output: false
  favorite_music:
    output: false
  schools:
    output: false
  testimonials:
    output: false
  conferences:
    output: false
